//! 模块（KO）供给语义（build-initrd.sh 的 Rust 接管 + Phase 3 组件化）。
//!
//! 两个清单：`modules-boot.conf`（initramfs，挂 root 前必需的冻结基础集，
//! 文件在 infra/，boot 阶段附加组件条目追加在其后）与 `modules.conf`
//! （rootfs，switch_root 后加载，**完全由组件 require 并集生成**，不再有
//! 手写源文件）。行格式 `<module> [key=val ...]`：首 token 是模块名，
//! 其余 token 由 VM 内 init 原样传给 insmod；`#` 注释与空行跳过。

use std::path::Path;

use anyhow::Context;

use crate::progress::Progress;

/// 组件计划投影出的模块清单：`boot_extra` 追加在 modules-boot.conf 冻结
/// 基础集之后（initramfs 阶段），`runtime` 生成 /lib/modules/modules.conf。
#[derive(Debug, Default, Clone, PartialEq)]
pub(crate) struct Modules {
    pub boot_extra: Vec<String>,
    pub runtime: Vec<String>,
}

/// conf 行 / 组件 require 条目的模块名（首 token）。
pub(crate) fn module_name(line: &str) -> &str {
    line.split_whitespace().next().unwrap_or_default()
}

/// 解析 conf 文件：返回模块名列表（保持声明顺序 —— 依赖手工排序是冻结语义）。
pub(crate) fn parse(conf: &Path) -> Vec<String> {
    let Ok(text) = std::fs::read_to_string(conf) else {
        return Vec::new();
    };
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .filter_map(|l| l.split_whitespace().next().map(str::to_string))
        .collect()
}

/// 在内核树中定位 `<mod>.ko`（首个命中，等价 `find -print -quit`）；
/// 兜底 `infra/testcases/<mod>.ko`。公开给 verify 的模块存在性检查复用。
pub(crate) fn find_ko(kernel_path: &Path, infra_dir: &Path, module: &str) -> Option<std::path::PathBuf> {
    let out = std::process::Command::new("find")
        .arg(kernel_path)
        .arg("-name")
        .arg(format!("{module}.ko"))
        .arg("-print")
        .arg("-quit")
        .output()
        .ok()?;
    let out_text = String::from_utf8_lossy(&out.stdout).to_string();
    let first = out_text.lines().next();
    if let Some(p) = first.filter(|s| !s.is_empty()) {
        return Some(std::path::PathBuf::from(p));
    }
    let fallback = infra_dir.join("testcases").join(format!("{module}.ko"));
    fallback.is_file().then_some(fallback)
}

/// 拷贝模块名清单声明的全部 `.ko` 到 dest，并把生成的 conf 文本写入
/// `dest/<conf_name>`（VM 内 init 从 conf 读取加载顺序与 insmod 参数；
/// 文本支持 `#` 注释与空行，两个 init 均跳过）。缺 `.ko` 构建期报错
/// （退出码非 0，冻结语义）。
pub(crate) fn copy_module_list(
    dest: &Path,
    modules: &[String],
    conf_text: &str,
    conf_name: &str,
    kernel_path: &Path,
    infra_dir: &Path,
    progress: &mut Progress,
) -> anyhow::Result<()> {
    std::fs::create_dir_all(dest)?;
    if modules.is_empty() {
        progress.line("  (no kernel modules in this stage's list)");
    } else {
        progress.line(&format!("Copying {} kernel module(s)...", modules.len()));
    }
    for module in modules {
        let Some(ko) = find_ko(kernel_path, infra_dir, module) else {
            anyhow::bail!("Module {module}.ko not found");
        };
        std::fs::copy(&ko, dest.join(format!("{module}.ko")))
            .with_context(|| format!("copy {} failed", ko.display()))?;
    }
    std::fs::write(dest.join(conf_name), conf_text)
        .with_context(|| format!("write {conf_name} failed"))?;
    Ok(())
}

/// 组装 initramfs 的 boot 清单：modules-boot.conf 冻结基础集 + 组件
/// boot 附加条目（conf 文本 = 基础集原文 + 附加行，顺序即加载顺序）。
/// 返回 (模块名清单, 生成 conf 文本)。
pub(crate) fn boot_set(base_conf: &Path, extra: &[String]) -> anyhow::Result<(Vec<String>, String)> {
    let mut names = parse(base_conf);
    let mut text = std::fs::read_to_string(base_conf).unwrap_or_default();
    if !text.is_empty() && !text.ends_with('\n') {
        text.push('\n');
    }
    for line in extra {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        text.push_str(line);
        text.push('\n');
        let name = module_name(line);
        if !names.iter().any(|n| n == name) {
            names.push(name.to_string());
        }
    }
    Ok((names, text))
}

/// 由 runtime 条目生成 modules.conf 文本（带生成头注释）。
pub(crate) fn runtime_conf_text(entries: &[String]) -> String {
    let mut text =
        String::from("# generated by builder from virtuoso.toml [components.*] require\n");
    for line in entries {
        text.push_str(line.trim());
        text.push('\n');
    }
    text
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_skips_comments_and_args() {
        let dir = std::env::temp_dir().join(format!("builder-modconf-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let conf = dir.join("modules.conf");
        std::fs::write(
            &conf,
            "# comment\ncrc64\nnvme-core  poll_queues=2\n\n  # indented\next4\n",
        )
        .unwrap();
        let mods = parse(&conf);
        assert_eq!(mods, ["crc64", "nvme-core", "ext4"]);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn boot_set_appends_extra_without_duplicating_names() {
        let dir = std::env::temp_dir().join(format!("builder-bootset-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let conf = dir.join("modules-boot.conf");
        std::fs::write(&conf, "# base\nvirtio_blk\next4\n").unwrap();
        let (names, text) = boot_set(
            &conf,
            &["crc64".into(), "virtio_blk".into(), "x  arg=1".into()],
        )
        .unwrap();
        assert_eq!(names, ["virtio_blk", "ext4", "crc64", "x"]);
        assert!(text.starts_with("# base\nvirtio_blk\next4\n"));
        assert!(text.contains("crc64\n"));
        assert!(text.ends_with("x  arg=1\n"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn runtime_conf_text_has_generated_header() {
        let text = runtime_conf_text(&["virtio_console".into(), "crc64".into()]);
        assert!(text.starts_with("# generated by builder"));
        assert!(text.contains("virtio_console\ncrc64\n"));
    }
}
