//! 非 Linux 宿主的交叉编译接线（macOS → guest Linux 静态 ELF）。
//!
//! 单一机制：`zig cc -target <triple>` 包装脚本。zig 自带 musl sysroot 与
//! lld，任意宿主可产出静态 Linux ELF，一个依赖（`brew install zig`）覆盖
//! C 用例与 Rust 两条线：
//! - C 用例：包装脚本作为 `CMAKE_C_COMPILER`（CMake 编译器探测一次通过）；
//! - Rust 用例 / tools：经 `CARGO_TARGET_<TRIPLE>_LINKER` 注入（no_std 用例
//!   的 `-nostdlib` 链接参数在 infra/testcases/rust/.cargo/config.toml）。
//!
//! Linux 宿主恒返回空接线（host cc 直构，行为不变）；`CC` /
//! `CARGO_TARGET_*_LINKER` 环境变量已设时对应接线让位（用户自带工具链优先）。

use std::path::{Path, PathBuf};

use common::{Arch, HostOs};

/// 一次构建的交叉接线（值语义；Linux 宿主全 None）。
#[derive(Debug, Default)]
pub struct CrossSetup {
    /// C 用例的 CMAKE_C_COMPILER（None = 无需交叉或 CC 已接管）。
    pub cc_wrapper: Option<PathBuf>,
    /// cargo 链接器注入（key 如 CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER）。
    pub cargo_linker: Option<(String, String)>,
    /// cargo rustflags 注入（key 如 CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS）。
    /// zig 接管链接时携带 `-C link-self-contained=no`：rustc 交出自含 crt1/libc，
    /// 由 zig 的 musl sysroot 供给，否则两边 crt1 重复定义 `_start`。
    pub cargo_rustflags: Option<(String, String)>,
    /// 目标 triple（如 aarch64-linux-musl；Linux 宿主为空，接线全 None）。
    pub triple: String,
    /// 呈现用说明（progress line / 诊断）。
    pub note: Option<String>,
}

impl CrossSetup {
    /// 目标 triple（CMake 交叉声明用；Linux 宿主为空）。
    pub fn target_triple(&self) -> &str {
        &self.triple
    }

    /// 把链接器/rustflags 注入应用到 cargo 命令（未接线 / 用户已设环境时为 no-op）。
    pub fn apply_to_cargo(&self, cmd: &mut std::process::Command) {
        if let Some((k, v)) = &self.cargo_linker {
            cmd.env(k, v);
        }
        if let Some((k, v)) = &self.cargo_rustflags {
            cmd.env(k, v);
        }
    }
}

/// 解析当前宿主的交叉接线。非 Linux 宿主且 CC、zig 皆缺 → 显式报错
/// （fail fast，好过把 Apple clang 交给 CMake 后的连串编译错）。
pub fn setup(arch: Arch, build_dir: &Path) -> anyhow::Result<CrossSetup> {
    if HostOs::current() == HostOs::Linux {
        return Ok(CrossSetup::default());
    }
    let triple = arch.zig_triple();
    let linker_key = format!(
        "CARGO_TARGET_{}_LINKER",
        arch.rust_musl_triple().to_uppercase().replace('-', "_")
    );

    if std::env::var_os("CC").is_some() && std::env::var_os(&linker_key).is_some() {
        // 用户自带全套交叉工具链
        return Ok(CrossSetup {
            triple: triple.to_string(),
            note: Some("cross: CC / CARGO_TARGET_*_LINKER 已由环境接管".into()),
            ..Default::default()
        });
    }
    let Some(zig) = common::fsutil::which_path("zig") else {
        anyhow::bail!(
            "非 Linux 宿主编译 guest 用例需要 zig（brew install zig）\n  \
             或自带工具链：CC=<cross-gcc> + CARGO_TARGET_{linker_key}=<linker>"
        );
    };
    let _ = zig; // PATH 命中即可，脚本内按名调用

    let dir = build_dir.join("cross");
    std::fs::create_dir_all(&dir)?;
    let wrapper = dir.join(format!("zig-cc-{}.sh", arch.name()));
    std::fs::write(
        &wrapper,
        format!("#!/bin/sh\n# generated by builder::cross — zig cc wrapper for {triple}\nexec zig cc -target {triple} \"$@\"\n"),
    )?;
    common::fsutil::set_executable(&wrapper)?;

    let rustflags_key = format!(
        "CARGO_TARGET_{}_RUSTFLAGS",
        arch.rust_musl_triple().to_uppercase().replace('-', "_")
    );
    let cargo_linker = if std::env::var_os(&linker_key).is_none() {
        Some((linker_key.clone(), wrapper.display().to_string()))
    } else {
        None
    };
    Ok(CrossSetup {
        cc_wrapper: if std::env::var_os("CC").is_none() {
            Some(wrapper.clone())
        } else {
            None
        },
        cargo_linker,
        cargo_rustflags: if std::env::var_os(&rustflags_key).is_none() {
            Some((rustflags_key, "-C link-self-contained=no".into()))
        } else {
            None
        },
        triple: triple.to_string(),
        note: Some(format!("cross: zig cc -target {triple}")),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn linker_env_key_shape() {
        // 与 setup() 内拼接规则互为镜像，防拼写漂移
        let key = format!(
            "CARGO_TARGET_{}_LINKER",
            Arch::Arm64
                .rust_musl_triple()
                .to_uppercase()
                .replace('-', "_")
        );
        assert_eq!(key, "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER");
    }

    #[test]
    fn linux_host_setup_is_empty() {
        // 本测试恒在 Linux 跑（CI 与开发机均为 Linux）；Darwin 分支由
        // 真机验收覆盖
        if HostOs::current() == HostOs::Linux {
            let s = setup(Arch::Arm64, Path::new("/tmp")).unwrap();
            assert!(s.cc_wrapper.is_none());
            assert!(s.cargo_linker.is_none());
        }
    }
}
